# Generated by Django 5.0.6 on 2024-06-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0003_alter_boardstate_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardstate',
            name='state',
            field=models.TextField(),
        ),
    ]
